---
- name: Install git
  homebrew:
    name: git
    state: present

- name: Install git-crypt
  homebrew:
    name: git-crypt
    state: present

- name: Install hub
  homebrew:
    name: hub
    state: present

- name: Copy hub config
  template:
    src: hub.j2
    dest: "{{ lookup('env', 'HOME') }}/.config/hub"
    mode: '0644'

- name: 'Copy gitconfig'
  template:
    src: gitconfig.j2
    dest: "{{ lookup('env', 'HOME') }}/.gitconfig"
    mode: '0644'
