---
- name: Update and Upgrade all
   homebrew:
     update_homebrew: yes
     upgrade_all: yes

- name: Install packages
  homebrew:
    name: "{{ item }}"
    state: present
  with_items: homebrew_packages
