---
- name: Install packages
  homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_packages }}"

- name: Enable homebrew/completions tap
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  notify: Update homebrew
  with_items: "{{ homebrew_taps }}"

- meta: flush_handlers
