---
- name: Update and Upgrade all
  homebrew:
    update_homebrew: yes
    upgrade_all: yes
  tags:
    - update

- name: Enable homebrew taps
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  notify: Update homebrew
  with_items: "{{ homebrew_taps }}"

- name: Install cask packages
  homebrew_cask:
    name: "{{ item.name }}"
    state: present
    #install_options: "{{ item.install_options|default() }}"
    #update_homebrew: yes
  with_items: "{{ homebrew_cask_packages }}"

- name: Install packages
  homebrew:
    name: "{{ item.name }}"
    state: latest
    install_options: "{{ item.install_options|default() }}"
  with_items: "{{ homebrew_packages }}"

- meta: flush_handlers
