# Set up Apple cusomizatons
---
  #- name: Show hidden files in Finder
  #    command: defaults write com.apple.finder AppleShowAllFiles TRUE
- name: Disable ds_store for remote shares
  command: defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

- name: Restart Finder
  command: killall Finder
