---
- name: Create ~/git directory
  file:
    path: "{{ lookup('env', 'HOME') }}/git"
    owner: "{{ username }}"
    mode: '0755'
    state: directory

- name: Create ~/docker directory
  file:
    path: "{{ lookup('env', 'HOME') }}/docker"
    owner: "{{ username }}"
    mode: '0755'
    state: directory

#- name: Create /docker  volume directory
# become: true
# become_method: sudo
# file:
#   path: /docker
#   owner: "{{ lookup('env', 'USER') }}"
#   mode: '0755'
#   state: directory
