---
- name: Create ~/scm directory
  file:
    path: "{{ lookup('env', 'HOME') }}/scm"
    owner: "{{ username }}"
    mode: '0755'
    state: directory

- name: Create ~/docker directory
  file:
    path: "{{ lookup('env', 'HOME') }}/docker"
    owner: "{{ username }}"
    mode: '0755'
    state: directory

- name: Create ~/go directory
  file:
    path: "{{ lookup('env', 'HOME') }}/go"
    owner: "{{ lookup('env', 'USER') }}"
    mode: 0755
    state: directory

- name: Create ~/.aws/cli directory
  file:
    path: "{{ lookup('env', 'HOME')}}/.aws/cli"
    owner: "{{ lookup('env', 'USER') }}"
    state: directory

- name: Create ~/.passwd directory
  file:
    path: "{{ lookup('env', 'HOME')}}/.passwd"
    owner: "{{ lookup('env', 'USER')}}"
    state: directory

#- name: Create /docker  volume directory
# become: true
# become_method: sudo
# file:
#   path: /docker
#   owner: "{{ lookup('env', 'USER') }}"
#   mode: '0755'
#   state: directory
