---
- name: Create ~/git directory
  file:
    path: "{{ lookup('env', 'HOME') }}/git"
    owner: "{{ username }}"
    group: staff
    mode: '0755'
    state: directory

- name: Create ~/docker directory
  file:
    path: "{{ lookup('env', 'HOME') }}/docker"
    owner: "{{ username }}"
    group: staff
    mode: '0755'
    state: directory
