---
gem_packages:
  - 'puppet'
  - 'puppet-lint'
  - 'facter'
  - 'puppet_forge'
  - 'librarian-puppet'
  - 'github_changelog_generator'

pip_packages:
  - 'boto'
  - 'jmespath'
  #- 'livestreamer'
  - 'PyYAML'
  - 'python-ldap'
