---
homebrew_taps:
  - 'homebrew/versions'
  - 'homebrew/completions'

homebrew_packages:
  - { name: 'coreutils' }
  - { name: 'bash' }
  - { name: 'bash-completion' }
  - { name: 'pwgen' }
  - { name: 'keychain' }
  - { name: 'curl' }
  - { name: 'pinentry' }
  - { name: 'hub' }
  - { name: 'gist' }
  - { name: 'jq' }
  - { name: 'terraform' }
  - { name: 'awscli' }
  - { name: 'ansible' }
  - { name: 'dos2unix' }
  - { name: 'watch' }
  - { name: 'subversion' }
  - { name: 'swaks' }
  - { name: 'ipcalc' }
  - { name: 'packer' }
  - { name: 'mtr' }
  - { name: 'sqlite' }
  - { name: 'unrar' }
  - { name: 'urlview' }
  - { name: 'ssh-copy-id' }
  - { name: 'go' }
  - { name: 'htop' }
  - { name: 'wget' }
  - { name: 'lastpass-cli', install_options: "with-pinentry,with-doc" }
  - { name: 'livestreamer' }
  - { name: 'ffmpeg' }
  - { name: 'shellcheck' }
